fix: Improve Static Server Reliability
NuroDev/astro-bun pull request #11
Opened 2024-12-23 18:04 UTC by lilnasy

# Changes
- Closes #4
- Astro SSR manifest is not exactly public API. If it works it works, but if it doesn't we should use something else.
- In this case, optimized images are not included in the "assets" list, which the adapter relied upon.
- Updated the logic to read the client directory on server boot and use the found files instead of the assets list in the SSR manifest.

![image](https://github.com/user-attachments/assets/e5971fbd-9d74-482a-9bff-285cfa44f399)

2024-12-23 23:23 UTC, NuroDev requested changes

2024-12-23 23:23 UTC, NuroDev commented on package/src/index.ts
> +  }
Please restore using `defineIntegration` with the `OptionsSchema` for this as it makes managing the validation of everything cleaner and easier to manage long time.

Instead of having an `if` check for every option just update the `OptionsSchema` to include the `unix` property.

2024-12-23 23:23 UTC, NuroDev commented on package/src/index.ts
> +      'astro:config:done': params => {
Please make sure to run the `format` and/or `lint` scripts to format the code correctly.

2024-12-23 23:23 UTC, NuroDev commented on package/src/server/index.ts
> +    }
This could probably be simplified into an object spread with a ternary like so:
```ts
_server = Bun.serve({
	error: (error) => new Response(`<pre>${error}\n${error.stack}</pre>`, {
		headers: { 'Content-Type': 'text/html' },
	}),
	fetch: handler(manifest, options),
	...(unix ? {
		unix,
	} : {
		hostname,
		port,
	})
});
```

2024-12-23 23:23 UTC, NuroDev commented on package/src/server/index.ts
> +async function getStaticAssets(clientDir: string) {
```suggestion
async function getStaticAssets(clientDir: string): Promise<Set<string>> {
```

2024-12-23 23:23 UTC, NuroDev commented on package/src/server/index.ts
> +function prependForwardSlash(pth: string) {
```suggestion
function prependForwardSlash(pth: string): string {
```

2024-12-23 23:23 UTC, NuroDev commented on package/src/server/index.ts
> +function appendForwardSlash(pth: string) {
```suggestion
function appendForwardSlash(pth: string): string {
```

2024-12-23 23:23 UTC, NuroDev commented on package/src/server/index.ts
> +function resolveClientDir(options: InternalOptions) {
```suggestion
function resolveClientDir(options: InternalOptions): string {
```

2024-12-23 23:23 UTC, NuroDev commented on package/src/server/index.ts
> +  // walk up the parent folders until you find the one that is the root of the server entry folder. This is how we find the client folder relatively.
```suggestion
  // Walk up the parent folders until you find the one that is the root of the server entry folder. This is how we find the client folder relatively.
```

2024-12-23 23:23 UTC, NuroDev commented on package/src/types.ts
All of the changes here seem to replace & ignore the Zod validation schemas in `package/src/validators.ts`?

2024-12-23 23:24 UTC, NuroDev commented
It also seems you have based this branch off of your branch used for #10 so the 2 you've put 2 PR's into 1.

2024-12-23 23:32 UTC, lilnasy commented on package/package.json
This is from https://github.com/NuroDev/astro-bun/pull/10. The reasoning was tsup.

![image](https://github.com/user-attachments/assets/eb329ffa-2d21-4a9a-b444-ef9ffe8d5629)

2024-12-23 23:34 UTC, lilnasy commented on package/src/index.ts
> +  }
Sure. How should the options be documented instead?

Since zod schemas can't directly be used to infer type while maintaining type docs, astro defines the configuration twice: once as the zod schema, and once as the typescript interface.

2024-12-23 23:42 UTC, lilnasy commented on package/src/types.ts
Yes, that's somewhat intentional.

Using `z.infer` would remove hover documentation. So rewriting the schema as an interface is necessary. Astro's config does the same.

Additionally, so far they were only being used to validate internal options (assets, host, port), which were ignored if provided by the user. So their presence in the options schema is also misleading. For example `adapter: bun({ port: 80 })` has never had any effect but it was present in the adapter parameter types anyway.

2024-12-23 23:46 UTC, NuroDev commented on package/package.json
Ah okay, that makes sense 👍

2024-12-23 23:49 UTC, NuroDev commented on package/src/index.ts
> +  }
The existing Zod schema documentation system does infer the type docs.
![CleanShot 2024-12-23 at 11  48 19@2x](https://github.com/user-attachments/assets/896edc0d-6a7b-496e-b681-f75ed1d4ac6c)

2024-12-23 23:53 UTC, lilnasy commented on package/src/index.ts
> +  }
That's great! I'll edit the other PR.

2024-12-23 23:55 UTC, NuroDev commented on package/src/index.ts
> +  }
Ah I see what you mean now. In the bundled types don't infer / copy the type docs.
![CleanShot 2024-12-23 at 11  54 08@2x](https://github.com/user-attachments/assets/2e461d23-618a-485f-8147-f21a273a8885)

In which case I'll push a new updated `Options` type structure that should fix this.

2024-12-24 00:02 UTC, lilnasy commented on package/src/index.ts
> +  }
It'd be great if you could add that as a commit to #10.

The corrected types for internal options are needed here in this PR:

https://github.com/NuroDev/astro-bun/pull/11/files#diff-218e1f81d8eccf28a9144e1b876a38b8dd3da491146e981e5816c8c48fd6afcdR138

2025-01-18 16:14 UTC, lilnasy commented
Marking as draft because it depends on types being corrected in #11.

2025-11-06 19:49 UTC, NuroDev commented
I've just gone ahead and published version `2.1.0` which adds unix socket support.
If you can fix the conflict / comments above I'll get this merged and published.

2025-11-10 17:45 UTC, adworacz commented
> I've just gone ahead and published version 2.1.0 which adds unix socket support.

Awesome, thank you very much for this!

2025-11-10 23:13 UTC, merged